version: 0.2
phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
  build:
    commands:
      - ./gradlew assembleRelease
      - ls -R
artifacts:
  files:
    - app/*.apk
  type: zip
  discard-paths: yes
  override-packing: true
  name: applicationapk