version: 0.2
phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
  build:
    commands:
      - ./gradlew assembleDebug
      - ls -R
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
  type: zip
  discard-paths: yes
  override-packing: true
  name: application