version: 0.2
phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
      nodejs: 10
  build:
    commands:
      - aws s3 cp "s3://${S3_BUCKET}/keystore/key.keystore" ./
      - export RELEASE_STORE_FILE=../key.keystore  
      - export RELEASE_KEY_ALIAS=key
      - export RELEASE_STORE_PASSWORD=$KEY_STORE_PASSWORD
      - export RELEASE_KEY_PASSWORD=$KEY_PASSWORD
      - echo $( date +"%H") 
      -  ./gradlew bumperInit -PbumperVersionName=$(date +"%Y.%m.%d.%H") -PbumperVersionCode=$(date +"%H")  
      - ./gradlew assembleRelease
      - npm install -g appcenter-cli
      - echo $APP_CENTER_TOKEN
      - appcenter login --token "$APP_CENTER_TOKEN"
      - appcenter apps list
      - appcenter distribute release --app TicTacToe --file app/build/outputs/apk/release/app-release.apk --group "test"


artifacts:  
  files:
    - app/build/outputs/apk/release/*.apk
  type: zip
  discard-paths: yes
  override-packing: true
  name: applicationapk