version: 0.2
phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
  build:
    commands:
      - echo $S3_BUCKET
      - aws s3 cp "s3://${S3_BUCKET}/keystore/key.keystore" ./
      - export RELEASE_STORE_FILE=../key.keystore  
      - export RELEASE_KEY_ALIAS=key
      -  ./gradlew bumperInit -PbumperVersionName=$(date +"%Y.%m.%d.%H") -PbumperVersionCode=$(date +"%H")  
      - ./gradlew assembleRelease
      - echo $KEY_PASSWORD > test.txt
artifacts:  
  files:
    - app/build/outputs/apk/release/*.apk
    - deploy.yml
    - test.txt
  type: zip
  discard-paths: yes
  override-packing: true
  name: applicationapk